/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "password": {                                    "en": "password",                                        "de": "Passwort",                                        "ru": "пароль",                                          "pt": "senha",                                           "nl": "wachtwoord",                                      "fr": "le mot de passe",                                 "it": "parola d'ordine",                                 "es": "contraseña",                                      "pl": "hasło",                                           "zh-cn": "密码"},
    "password from your web.smart-me.com account": { "en": "password from your web.smart-me.com account",     "de": "Passwort von Ihrem Konto bei web.smart-me.com",       "ru": "пароль от вашей учетной записи web.smart-me.com", "pt": "senha da sua conta web.smart-me.com",             "nl": "wachtwoord van uw web.smart-me.com-account",      "fr": "mot de passe de votre compte web.smart-me.com",   "it": "password dal tuo account web.smart-me.com",       "es": "contraseña de su cuenta web.smart-me.com",        "pl": "hasło z konta web.smart-me.com",                  "zh-cn": "来自您的web.smart-me.com帐户的密码"},
    "smgd adapter settings": {                       "en": "Adapter settings for smgd",                       "de": "Adaptereinstellungen für smgd",                   "ru": "Настройки адаптера для smgd",                     "pt": "Configurações do adaptador para smgd",            "nl": "Adapterinstellingen voor smgd",                   "fr": "Paramètres de l'adaptateur pour smgd",            "it": "Impostazioni dell'adattatore per smgd",           "es": "Configuración del adaptador para smgd",           "pl": "Ustawienia adaptera dla smgd",                    "zh-cn": "smgd的适配器设置"},
    "username": {                                    "en": "username",                                        "de": "Nutzername",                                      "ru": "имя пользователя",                                "pt": "nome de usuário",                                 "nl": "gebruikersnaam",                                  "fr": "Nom d'utilisateur",                               "it": "nome utente",                                     "es": "nombre de usuario",                               "pl": "Nazwa Użytkownika",                               "zh-cn": "用户名"},
    "username or email from your web.smart-me.com account": {"en": "username or email from your web.smart-me.com account", "de": "Benutzername oder E-Mail von Ihrem Konto bei web.smart-me.com", "ru": "имя пользователя или адрес электронной почты из вашей учетной записи web.smart-me.com", "pt": "nome de usuário ou e-mail da sua conta web.smart-me.com", "nl": "gebruikersnaam of e-mailadres van uw web.smart-me.com-account", "fr": "nom d'utilisateur ou e-mail de votre compte web.smart-me.com", "it": "nome utente o e-mail dal tuo account web.smart-me.com", "es": "nombre de usuario o correo electrónico de su cuenta web.smart-me.com", "pl": "nazwa użytkownika lub adres e-mail z konta web.smart-me.com", "zh-cn": "您的web.smart-me.com帐户的用户名或电子邮件"},
};